### ISSUE TITLE
error: decoding custom section component-type:reactor

### ISSUE THREAD

**Issue by sgysh** [bytecodealliance/component-docs#80]
https://component-model.bytecodealliance.org/language-support/python.html#running-components-from-python-applications

When using https://github.com/dicej/wasmtime-py following the steps written on the above page, I get the following error:

```
======================= Building component.wasm ===================
error: decoding custom section component-type:reactor

Caused by:
    0: record type must have at least one field (at offset 0xd)
Traceback (most recent call last):
  File "/wasmtime-py/ci/build-rust.py", line 45, in <module>
    main()
  File "/wasmtime-py/ci/build-rust.py", line 34, in main
    ).check_returncode()
      ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['wasm-tools', 'component', 'new', 'rust/target/wasm32-wasi/release/bindgen.wasm', '--adapt', 'wasi_snapshot_preview1=ci/wasi_preview1_component_adapter.wasm', '-o', 'rust/target/component.wasm']' returned non-zero exit status 1.
```

When I use https://github.com/bytecodealliance/wasmtime-py instead, there are no errors.

**Comment by vados-cosmonic** [comment]
Hey @sgysh do you still run into this? We should all be using https://github.com/bytecodealliance/wasmtime-py at this point AFAIK so hopefully this isn't an issue any more

**Comment by sgysh** [comment]
I’m no longer facing this issue. Thank you.
